name: probashi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/scan.png
    - assets/images/logo.png
    - assets/images/verify_phone_human.jpg
    - assets/data/serviceData.json
    - assets/data/helpData.json
    - assets/data/downloadCardData.json
  